apiVersion: v1
kind: Pod
metadata:
  name: ${podName}
spec:
  containers:
    - image: ${dockerImage}
      name: container-default
      ports:
        - containerPort: ${containerPort}
          protocol: TCP