apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-${appLabel}
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: ${appLabel}
  template:
    metadata:
      name: ${appLabel}
      labels:
        app: ${appLabel}
    spec:
      containers:
        - image: ${dockerImage}
          name: container_1